cloud:
  aws:
    s3:
      bucket: moosongsong/foreignlove
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

AWS_S3_BUCKET_URL: https://moosongsong.s3.ap-northeast-2.amazonaws.com/foreignlove/